"use client";

import { useEffect, useRef, useState } from "react";
import BrandLogo from "./BrandLogo";
import styles from "./SiteFooter.module.css";
import ConfettiBurst from "./ConfettiBurst";

const disciplines=["Electrical Engineering","Mechanical Engineering","Fire Protection","Plumbing"];
const markets=["New York","New Jersey","Pennsylvania","Massachusetts","Connecticut","North Carolina","Florida","Colorado","California","Other"];
const projectTypes=["Commercial","Data Centers / Mission Critical","Education / Higher Education","Healthcare","Hospitality","Infrastructure / Civil","Transportation / Aviation / Rail","Water / Wastewater","Other"];
const inquiryMessages={hiring:"Hello,\nI am interested in discussing our company hiring needs and learning how AGILE may be able to support our recruiting efforts. Please reach back to me to discuss our current priorities and hiring needs.  Thank you.",services:"Hello,\nI am interested in learning more about AGILE's recruiting services, including recruiting fees and placement guarantees. Please reach back to me so we can discuss how your services may support our company.  Thank you."};
function formatPhone(value){const digits=value.replace(/\D/g,"").slice(0,10);if(digits.length<4)return digits;if(digits.length<7)return `(${digits.slice(0,3)}) ${digits.slice(3)}`;return `(${digits.slice(0,3)}) ${digits.slice(3,6)}-${digits.slice(6)}`;}

export default function SiteFooter() {
  const[clientOpen,setClientOpen]=useState(false);const[sending,setSending]=useState(false);const[status,setStatus]=useState("");const[inquirySubject,setInquirySubject]=useState("hiring");const[clientMessage,setClientMessage]=useState(inquiryMessages.hiring);const[clientPhone,setClientPhone]=useState("");const[celebrating,setCelebrating]=useState(false);const clientModalRef=useRef(null);const[trustOpen,setTrustOpen]=useState(false);const trustRef=useRef(null);
  useEffect(()=>{if(!trustOpen)return;function onDocClick(event){if(trustRef.current&&!trustRef.current.contains(event.target))setTrustOpen(false);}document.addEventListener("mousedown",onDocClick);return()=>document.removeEventListener("mousedown",onDocClick);},[trustOpen]);
  function openClientSupport(){setStatus("");setInquirySubject("hiring");setClientMessage(inquiryMessages.hiring);setClientPhone("");setCelebrating(false);setClientOpen(true);}
  useEffect(()=>{function openFromAddress(){if(window.location.hash==="#client-hiring-support")openClientSupport();}openFromAddress();window.addEventListener("hashchange",openFromAddress);return()=>window.removeEventListener("hashchange",openFromAddress);},[]);
  function changeInquirySubject(event){const value=event.target.value;setInquirySubject(value);setClientMessage(inquiryMessages[value]||"");}
  async function submitClient(event){event.preventDefault();const form=event.currentTarget;setSending(true);setStatus("");setCelebrating(false);try{const response=await fetch("/api/client-hiring-support",{method:"POST",body:new FormData(form)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||"Unable to send your request.");form.reset();setInquirySubject("hiring");setClientMessage(inquiryMessages.hiring);setClientPhone("");setStatus("Success! Your message has been sent. We look forward to connecting soon!");setCelebrating(true);window.requestAnimationFrame(()=>{clientModalRef.current?.scrollTo({top:0,behavior:"smooth"});});window.setTimeout(()=>setCelebrating(false),2600);}catch(error){setStatus(error.message||"We could not send your request. Please try again.");}finally{setSending(false);}}
  const success=status.startsWith("Success!");
  return <><footer className={`site-footer ${styles.footer}`}><div className={`container footer-grid ${styles.grid}`}>
    <div className={styles.brandBlock}><BrandLogo className={styles.footerLogo} /><p className={styles.brandCopy}>Specialized Recruiting and Professional Representation for Architects, Engineers, and Construction Professionals.</p></div>
    <div><h2>You&apos;ve built the experience.<br/><em>Let&apos;s explore what comes next.</em></h2><p className={`footer-eyebrow ${styles.eyebrow}`}>STATES SERVED</p><p>New York · New Jersey · Pennsylvania · Massachusetts · Connecticut · North&nbsp;Carolina · Florida · Colorado · California</p><div className={`footer-actions ${styles.actions}`}><a href="/careers/#positions">SEARCH CAREERS</a><button type="button" onClick={openClientSupport}>CLIENT HIRING SUPPORT</button></div></div>
    <div><p className={`footer-eyebrow ${styles.eyebrow}`}>CONNECT WITH AGILE</p><p><a className={styles.emailLink} href="mailto:careers@agileconsultingsolutions.com" target="_blank" rel="noopener noreferrer">careers@agileconsultingsolutions.com</a></p><p><strong>MAIN OFFICE 407-868-7254</strong></p><p>Professional Career Consultants.</p><p className={`footer-eyebrow ${styles.eyebrow}`}>AVAILABLE HOURS · EASTERN</p><p>Monday–Friday · 8:00 AM–8:30 PM</p><p>Saturday · 9:00 AM–12:30 PM</p><p><em>Additional availability by request.</em></p></div>
  </div><div className={`footer-bottom ${styles.bottom}`}><div className={`container footer-bottom-inner ${styles.bottomInner}`}><span>© 2026 AGILE Business Consulting · All Rights Reserved</span><span>Personal Career Support · No Account Setup Required</span>
    <div ref={trustRef} className={styles.trustWrap}>
      <button type="button" className={`${styles.trustToggle} ${trustOpen?styles.trustToggleOpen:""}`} aria-expanded={trustOpen} onClick={()=>setTrustOpen(v=>!v)}>
        Trust &amp; Security <span className={styles.trustChev}></span>
      </button>
      <div className={`${styles.trustPanel} ${trustOpen?styles.trustPanelOpen:""}`}>
        <a href="/privacy-policy" onClick={()=>setTrustOpen(false)}>Privacy Policy</a>
        <a href="/candidate-security" onClick={()=>setTrustOpen(false)}>Candidate Security</a>
        <a href="/recruiting-scam-warning" onClick={()=>setTrustOpen(false)}>Recruiting Scam Warning</a>
      </div>
    </div>
    <a href="/careers/#contact">Start a Conversation</a></div></div></footer>
  {clientOpen?<div className={styles.overlay} role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setClientOpen(false);}}><section ref={clientModalRef} className={styles.clientModal} role="dialog" aria-modal="true" aria-labelledby="client-support-title">{celebrating?<ConfettiBurst className={styles.confettiBurst} />:null}<button className={styles.close} type="button" onClick={()=>setClientOpen(false)} aria-label="Close client hiring support">×</button><p className={styles.clientEyebrow}>CLIENT HIRING SUPPORT</p><h2 id="client-support-title">Tell us where your team needs help.</h2><p className={styles.clientIntro}>Share the essentials and an AGILE recruiting consultant will reach back to you directly.</p>{status?<p className={`${styles.clientStatus} ${success?styles.clientSuccess:styles.clientError} ${celebrating?styles.statusPop:""}`} role="status" aria-live="polite">{status}</p>:null}<form className={styles.clientForm} onSubmit={submitClient}>
  <label>Name *<input name="name" required placeholder="First and last name" /></label><label>Business Title<input name="businessTitle" placeholder="Title / role" /></label><label>Email *<input type="email" name="email" required placeholder="name@company.com" /></label><label>Phone<input type="tel" name="phone" placeholder="(***) ***-****" inputMode="tel" value={clientPhone} onChange={event=>setClientPhone(formatPhone(event.target.value))} /></label><label className={styles.full}>Company Website / URL<input type="text" name="companyUrl" inputMode="url" placeholder="company.com" /></label>
  <label>Location<select name="location" defaultValue=""><option value="">Choose location</option>{markets.map(item=><option key={item}>{item}</option>)}</select></label><label>Best Time to Reach You<select name="bestTime" defaultValue=""><option value="">Choose time</option><option>Morning · 8 AM–11 AM</option><option>Midday · 11 AM–2 PM</option><option>Afternoon · 2 PM–5 PM</option><option>Evening · 5 PM–8 PM</option><option>Flexible</option></select></label>
  <label>Discipline Needed<select name="discipline1" defaultValue=""><option value="">Choose discipline</option>{disciplines.map(item=><option key={item}>{item}</option>)}</select></label><label>Second Discipline · Optional<select name="discipline2" defaultValue=""><option value="">None</option>{disciplines.map(item=><option key={item}>{item}</option>)}</select></label><label>Third Discipline · Optional<select name="discipline3" defaultValue=""><option value="">None</option>{disciplines.map(item=><option key={item}>{item}</option>)}</select></label><label>Primary Project Type<select name="projectType1" defaultValue=""><option value="">Choose project type</option>{projectTypes.map(item=><option key={item}>{item}</option>)}</select></label><label>Additional Project Type · Optional<select name="projectType2" defaultValue=""><option value="">None</option>{projectTypes.map(item=><option key={item}>{item}</option>)}</select></label><label>Hiring Timing<select name="hiringTiming" defaultValue=""><option value="">Choose timing</option><option>Immediately</option><option>Within 30 days</option><option>Within 60–90 days</option><option>Planning ahead</option></select></label>
  <label className={styles.full}>Inquiry Subject<select name="inquirySubject" value={inquirySubject} onChange={changeInquirySubject}><option value="hiring">Interested in discussing our company hiring needs</option><option value="services">Interested in AGILE services, recruiting fees and placement guarantees</option></select></label><label className={styles.full}>Message<textarea name="message" rows="5" value={clientMessage} onChange={event=>setClientMessage(event.target.value)} /></label><div className={`${styles.full} ${styles.clientActions}`}><button type="submit" disabled={sending}>{sending?"Sending...":"Please Reach Back to Me"}</button></div></form></section></div>:null}</>;
}
